name: LJNewsFeed
favicon: null
layout_spectrum: 0.01021
typography_spectrum: 0.93844
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ccbc8b'
    - '#383969'
    - '#0e6579'
    - '#91847b'
    - '#7f5c35'
  brandStrength: 0.5625
  lightness: 0.4375
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: f9f9ab00-2417-4cb1-b19d-80f9851c24a1
    url: null
