name: LJNewsFeed
favicon: null
layout_spectrum: 0.01021
typography_spectrum: 0.93844
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ccbc8b'
    - '#383969'
    - '#0e6579'
    - '#91847b'
    - '#7f5c35'
  brandStrength: 0.875
  lightness: 0.25
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: 'null'
    url: null
