name: LJNewsFeed
favicon: null
layout_spectrum: 0.01021
typography_spectrum: 0.93844
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8d0011'
    - '#d8d2bc'
    - '#fefdfe'
    - '#9f887a'
    - '#b1392b'
  brandStrength: 0.5625
  lightness: 0.6875
  saturation: 0.125
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: 'null'
    url: null
